theme: minima
google_analytics: UA—19799395-2
lang: hu
author: Ferenci Tamás
email: tamas.ferenci@medstat.hu
title: Ferenci Tamás elektronikus jegyzetei
description: Valószínűségszámítás, statisztika, biostatisztika, R programcsomag
plugins:
  - jekyll-sitemap
